import type ExcelJS from "exceljs";

const LEGACY_NA = "n/a";

function isEmptyLabel(label: string): boolean {
  const trimmed = label.trim();
  return !trimmed || trimmed.toLowerCase() === LEGACY_NA;
}

function isBlankCellValue(value: ExcelJS.CellValue | undefined | null): boolean {
  if (value === null || value === undefined || value === "") {
    return true;
  }
  if (value instanceof Date) {
    return false;
  }
  if (typeof value === "object" && value !== null && "formula" in value) {
    return false;
  }
  if (typeof value === "number" || typeof value === "boolean") {
    return false;
  }
  const text = String(value).trim();
  return text === "" || text.toLowerCase() === LEGACY_NA;
}

/** Soft row fills that stay readable in Excel. */
const GROUP_ROW_COLORS = [
  "FFDBEAFE", // blue
  "FFE9D5FF", // purple
  "FFBBF7D0", // green
  "FFFDE68A", // amber
  "FFFBCFE8", // pink
  "FF99F6E4", // teal
  "FFC7D2FE", // indigo
  "FFFECDD3", // rose
  "FFD9F99D", // lime
  "FFBAE6FD", // sky
  "FFE7E5E4", // stone
  "FFA5F3FC", // cyan
  "FFFED7AA", // orange
  "FFDDD6FE", // violet
  "FFFEF9C3", // pale yellow
  "FFCFFAFE", // light cyan
  "FFF5D0FE", // fuchsia
  "FFD1FAE5", // emerald
  "FFFFE4E6", // light rose
  "FFE0E7FF", // periwinkle
] as const;

const DEFAULT_GROUP_COLOR = "FFF3F4F6";

function hashLabel(label: string): number {
  let hash = 0;
  for (let index = 0; index < label.length; index += 1) {
    hash = (hash * 31 + label.charCodeAt(index)) >>> 0;
  }
  return hash;
}

/** Stable fill color for a course or category label. */
export function fillColorForGroup(label: string | undefined): string {
  const trimmed = label?.trim();
  if (!trimmed || isEmptyLabel(trimmed)) {
    return "FFFFFFFF";
  }

  const index = hashLabel(trimmed.toLowerCase()) % GROUP_ROW_COLORS.length;
  return GROUP_ROW_COLORS[index] ?? DEFAULT_GROUP_COLOR;
}

export function applyRowGroupColor(
  sheet: ExcelJS.Worksheet,
  rowNumber: number,
  columnCount: number,
  groupLabel: string | undefined,
): void {
  const groupFill: ExcelJS.Fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: fillColorForGroup(groupLabel) },
  };

  const row = sheet.getRow(rowNumber);
  for (let column = 1; column <= columnCount; column += 1) {
    const cell = row.getCell(column);
    if (isBlankCellValue(cell.value)) {
      cell.value = null;
      cell.style = {};
      continue;
    }
    cell.fill = groupFill;
  }
}

/** Re-apply row colors for every data row using the group column. */
export function refreshSheetGroupColors(
  sheet: ExcelJS.Worksheet,
  groupColumn: number,
  columnCount: number,
): void {
  for (let row = 2; row <= 5000; row += 1) {
    const groupValue = sheet.getRow(row).getCell(groupColumn).text?.trim();
    if (!groupValue) {
      break;
    }
    applyRowGroupColor(sheet, row, columnCount, groupValue);
  }
}

/** Convert HSL (h in [0,360), s & l in [0,1]) to an "FFRRGGBB" hex string. */
function hslToArgb(h: number, s: number, l: number): string {
  const chroma = (1 - Math.abs(2 * l - 1)) * s;
  const x = chroma * (1 - Math.abs(((h / 60) % 2) - 1));
  const m = l - chroma / 2;
  let r = 0;
  let g = 0;
  let b = 0;
  if (h < 60) [r, g, b] = [chroma, x, 0];
  else if (h < 120) [r, g, b] = [x, chroma, 0];
  else if (h < 180) [r, g, b] = [0, chroma, x];
  else if (h < 240) [r, g, b] = [0, x, chroma];
  else if (h < 300) [r, g, b] = [x, 0, chroma];
  else [r, g, b] = [chroma, 0, x];
  const channel = (value: number) =>
    Math.round((value + m) * 255)
      .toString(16)
      .padStart(2, "0")
      .toUpperCase();
  return `FF${channel(r)}${channel(g)}${channel(b)}`;
}

const GOLDEN_ANGLE = 137.508;

/**
 * Assign a guaranteed-unique color to each subject. The curated palette is used
 * first; once it is exhausted, extra colors are generated by rotating the hue.
 * Any color that would repeat one already given to a different subject is nudged
 * until its hex is unique — so two different classes never share a color.
 */
function assignDistinctColors(count: number): string[] {
  const used = new Set<string>();
  const colors: string[] = [];
  for (let index = 0; index < count; index += 1) {
    let candidate =
      index < GROUP_ROW_COLORS.length
        ? GROUP_ROW_COLORS[index]
        : hslToArgb((index * GOLDEN_ANGLE) % 360, 0.6, 0.84);
    let nudge = 0;
    while (used.has(candidate) && nudge < 720) {
      nudge += 1;
      candidate = hslToArgb((index * GOLDEN_ANGLE + nudge) % 360, 0.6, 0.84);
    }
    used.add(candidate);
    colors.push(candidate);
  }
  return colors;
}

/** A1-style column letter for a 1-based column index. */
function columnLetter(column: number): string {
  let result = "";
  let remaining = column;
  while (remaining > 0) {
    const part = (remaining - 1) % 26;
    result = String.fromCharCode(65 + part) + result;
    remaining = Math.floor((remaining - 1) / 26);
  }
  return result;
}

/** Worksheet rows are occupied when any cell across the record holds a value. */
function rowOccupied(
  sheet: ExcelJS.Worksheet,
  row: number,
  columnCount: number,
): boolean {
  for (let column = 1; column <= columnCount; column += 1) {
    if (!isBlankCellValue(sheet.getRow(row).getCell(column).value)) {
      return true;
    }
  }
  return false;
}

/**
 * Drive row colors with Excel conditional formatting keyed on the group column,
 * so each distinct subject gets its own color and a row recolors automatically
 * when its course/category is edited in Excel. One expression rule per distinct
 * value is applied across the whole record range; rules are rebuilt from scratch
 * each call so they always match the data currently in the sheet.
 */
export function applyGroupConditionalFormatting(
  sheet: ExcelJS.Worksheet,
  groupColumn: number,
  columnCount: number,
  endRow = 2000,
): void {
  // We own all conditional formatting on these sheets, so clear and rebuild.
  sheet.removeConditionalFormatting(undefined);

  const labels: string[] = [];
  const seen = new Set<string>();
  for (let row = 2; row <= endRow; row += 1) {
    if (!rowOccupied(sheet, row, columnCount)) {
      break;
    }
    const label = sheet.getRow(row).getCell(groupColumn).text?.trim() ?? "";
    if (isEmptyLabel(label)) {
      continue;
    }
    const key = label.toLowerCase();
    if (!seen.has(key)) {
      seen.add(key);
      labels.push(label);
    }
  }

  if (labels.length === 0) {
    return;
  }

  const groupLetter = columnLetter(groupColumn);
  const lastLetter = columnLetter(columnCount);
  const ref = `A2:${lastLetter}${endRow}`;
  const colors = assignDistinctColors(labels.length);

  const rules = labels.map((label, index) => {
    const argb = colors[index];
    // Excel string comparison is case-insensitive, so the stored casing is fine.
    const escaped = label.replace(/"/g, '""');
    return {
      type: "expression" as const,
      priority: index + 1,
      formulae: [`$${groupLetter}2="${escaped}"`],
      style: {
        fill: {
          type: "pattern" as const,
          pattern: "solid" as const,
          // dxf solid fills render via bgColor; set fgColor too for portability.
          bgColor: { argb },
          fgColor: { argb },
        },
      },
    };
  });

  sheet.addConditionalFormatting({ ref, rules });
}
